version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: risk-postgres
    restart: always
    environment:
      POSTGRES_DB: risk_engine
      POSTGRES_USER: risk_user
      POSTGRES_PASSWORD: risk_password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
